#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "H2 <=> H + H",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(4.577e+19,'cm^3/(mol*s)'), n=-1.4, Ea=(104380,'cal/mol'), T0=(1,'K')), efficiencies={'O': 12, 'O=C=O': 3.8, '[Ar]': 0, '[C-]#[O+]': 1.9, '[H][H]': 2.5, '[He]': 0}),
    longDesc = 
"""
Originally from reaction library: BurkeH2O2inArHe
""",
)

entry(
    index = 1,
    label = "Ar + H2 <=> Ar + H + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.84e+18,'cm^3/(mol*s)'), n=-1.1, Ea=(104380,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: BurkeH2O2inArHe
""",
)

entry(
    index = 2,
    label = "OH + H2 <=> H + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.16e+08,'cm^3/(mol*s)'), n=1.51, Ea=(3430,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: BurkeH2O2inArHe
""",
)

entry(
    index = 3,
    label = "H2O <=> H + OH",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(6.064e+27,'cm^3/(mol*s)'), n=-3.322, Ea=(120790,'cal/mol'), T0=(1,'K')), efficiencies={'N#N': 2, 'O': 0, 'O=C=O': 3.8, '[C-]#[O+]': 1.9, '[H][H]': 3, '[He]': 1.1, '[O][O]': 1.5}),
    longDesc = 
"""
Originally from reaction library: BurkeH2O2inArHe
""",
)

entry(
    index = 4,
    label = "H2O + H2O <=> H + OH + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.006e+26,'cm^3/(mol*s)'), n=-2.44, Ea=(120180,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: BurkeH2O2inArHe
""",
)

entry(
    index = 5,
    label = "OH + OH <=> O2 + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+11,'cm^3/(mol*s)'), n=0.51, Ea=(50500,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: BurkeH2O2inArHe
""",
)

entry(
    index = 6,
    label = "X + X + H2 <=> HX + HX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.046, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), coverage_dependence={'X(1)': {'a':0, 'm':-1, 'E':(0.0, 'J/mol')},}),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 7,
    label = "X + CO2 <=> CO2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.005, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 8,
    label = "COX <=> X + CO",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+11,'1/s'), n=0, Ea=(169500,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), coverage_dependence={'COX(23)': {'a':0, 'm':0, 'E':(-33000.0, 'J/mol')},}),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 9,
    label = "X + X + O2 <=> OX + OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.89e+21,'cm^5/(mol^2*s)'), n=-0.5, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 10,
    label = "OX + COX <=> X + CO2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.7e+21,'cm^2/(mol*s)'), n=0, Ea=(117600,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), coverage_dependence={'COX(23)': {'a':0, 'm':0, 'E':(-33000.0, 'J/mol')},}),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 11,
    label = "HX + CH2X <=> X + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.09e+22,'cm^2/(mol*s)'), n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), coverage_dependence={'HX(21)': {'a':0, 'm':0, 'E':(-2800.0, 'J/mol')},}),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 12,
    label = "HX + CH3X <=> X + X + CH4",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.3e+21,'cm^2/(mol*s)'), n=0, Ea=(50000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), coverage_dependence={'HX(21)': {'a':0, 'm':0, 'E':(-28000.0, 'J/mol')},}),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 13,
    label = "X + CH2X <=> HX + CHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(7.31e+18,'m^2/(mol*s)'), n=0, Ea=(58900,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), coverage_dependence={'CX(29)': {'a':0, 'm':0, 'E':(50000.0, 'J/mol')},}),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 14,
    label = "X + COX <=> OX + CX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.7e+15,'m^2/(mol*s)'), n=0, Ea=(236500,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), coverage_dependence={'COX(23)': {'a':0, 'm':0, 'E':(-33000.0, 'J/mol')},}),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 15,
    label = "X + CHX <=> HX + CX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.09e+22,'cm^2/(mol*s)'), n=0, Ea=(51700,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), coverage_dependence={'HX(21)': {'a':0, 'm':0, 'E':(-2800.0, 'J/mol')},}),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 16,
    label = "H2 + CX <=> CH2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.04, n=0, Ea=(29700,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), coverage_dependence={'CX(29)': {'a':0, 'm':0, 'E':(4600.0, 'J/mol')},}),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 17,
    label = "X + OX + CH4 <=> OHX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5e+18,'cm^5/(mol^2*s)'), n=0.7, Ea=(42000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), coverage_dependence={'OX(25)': {'a':0, 'm':0, 'E':(8000.0, 'J/mol')},}),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 18,
    label = "OHX + COX <=> HX + CO2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+15,'m^2/(mol*s)'), n=0, Ea=(38700,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), coverage_dependence={'COX(23)': {'a':0, 'm':0, 'E':(-30000.0, 'J/mol')},}),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 19,
    label = "X + OHX <=> OX + HX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(7.39e+15,'m^2/(mol*s)'), n=0, Ea=(77300,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), coverage_dependence={'OX(25)': {'a':0, 'm':0, 'E':(-73220.0, 'J/mol')},}),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 20,
    label = "X + OHX + CH4 <=> H2OX + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=1, n=0, Ea=(10000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 21,
    label = "X + H2O <=> H2OX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.75, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 22,
    label = "X + H2OX <=> HX + OHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.15e+15,'m^2/(mol*s)'), n=0, Ea=(101400,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), coverage_dependence={'OX(25)': {'a':0, 'm':0, 'E':(167360.0, 'J/mol')},}),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 23,
    label = "OX + H2OX <=> OHX + OHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+20,'cm^2/(mol*s)'), n=0, Ea=(90500,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), coverage_dependence={'OX(25)': {'a':0, 'm':0, 'E':(-240580.0, 'J/mol')},}),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006_adjusted
""",
)

entry(
    index = 24,
    label = "H + CH3 <=> CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.93e+14,'cm^3/(mol*s)'), n=0, Ea=(1.12968,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Matched reaction 57 H + CH3 <=> CH4 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_N-2CNO->O]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 57 H + CH3 <=> CH4 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_N-2CNO->O]
family: R_Recombination
""",
)

entry(
    index = 25,
    label = "CH3 + CH3 <=> C2H6",
    degeneracy = 0.5,
    kinetics = Arrhenius(A=(9.45e+14,'cm^3/(mol*s)'), n=-0.538, Ea=(135.1,'cal/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(2000,'K'), comment="""Matched reaction 9 CH3 + CH3 <=> C2H6 in R_Recombination/training
    This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 9 CH3 + CH3 <=> C2H6 in R_Recombination/training
This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing]
family: R_Recombination
""",
)

entry(
    index = 26,
    label = "H + C2H5 <=> C2H6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+14,'cm^3/(mol*s)','+|-',1e+13), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), comment="""Matched reaction 58 H + C2H5 <=> C2H6-2 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_N-2CNO->O_3R!H->C_Sp-3C-2CN]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 58 H + C2H5 <=> C2H6-2 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_N-2CNO->O_3R!H->C_Sp-3C-2CN]
family: R_Recombination
""",
)

entry(
    index = 27,
    label = "H2 + CO <=> CH2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.89e+09,'cm^3/(mol*s)'), n=1.16, Ea=(343.506,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2 H2 + CO <=> CH2O in 1,2_Insertion_CO/training
    This reaction matched rate rule [CO;H2]
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Matched reaction 2 H2 + CO <=> CH2O in 1,2_Insertion_CO/training
This reaction matched rate rule [CO;H2]
family: 1,2_Insertion_CO
""",
)

entry(
    index = 28,
    label = "H + HCO <=> CH2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.68e+10,'cm^3/(mol*s)'), n=0, Ea=(-18.9535,'kJ/mol'), T0=(1,'K'), Tmin=(1500,'K'), Tmax=(1900,'K'), comment="""Matched reaction 63 H + CHO <=> CH2O in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 63 H + CHO <=> CH2O in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O]
family: R_Recombination
""",
)

entry(
    index = 29,
    label = "CH3 + C2H5 <=> C3H8",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.23e+15,'cm^3/(mol*s)'), n=-0.562, Ea=(20.5,'cal/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(2000,'K'), comment="""Matched reaction 10 CH3 + C2H5 <=> C3H8 in R_Recombination/training
    This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Sp-3R!H-2R_3R!H->C_2R->C]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 10 CH3 + C2H5 <=> C3H8 in R_Recombination/training
This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Sp-3R!H-2R_3R!H->C_2R->C]
family: R_Recombination
""",
)

entry(
    index = 30,
    label = "H + C2H4 <=> C2H5",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(4.62e+08,'cm^3/(mol*s)'), n=1.64, Ea=(4.22584,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2541 H + C2H4 <=> C2H5-2 in R_Addition_MultipleBond/training
    This reaction matched rate rule [Cds-HH_Cds-HH;HJ]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 2541 H + C2H4 <=> C2H5-2 in R_Addition_MultipleBond/training
This reaction matched rate rule [Cds-HH_Cds-HH;HJ]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 31,
    label = "OH + CH3 <=> CH3OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.03e+13,'cm^3/(mol*s)','*|/',2), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Matched reaction 73 CH3 + OH <=> CH4O in R_Recombination/training
    This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_2R->C]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 73 CH3 + OH <=> CH4O in R_Recombination/training
This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_2R->C]
family: R_Recombination
""",
)

entry(
    index = 32,
    label = "H + CO <=> HCO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.18e+11,'cm^3/(mol*s)'), n=0, Ea=(11.3805,'kJ/mol'), T0=(1,'K'), Tmin=(345,'K'), Tmax=(449,'K'), comment="""Matched reaction 4 H + CO <=> CHO in R_Addition_COm/training
    This reaction matched rate rule [COm;H_rad]
    family: R_Addition_COm"""),
    longDesc = 
"""
Matched reaction 4 H + CO <=> CHO in R_Addition_COm/training
This reaction matched rate rule [COm;H_rad]
family: R_Addition_COm
""",
)

entry(
    index = 33,
    label = "CO + CH4 <=> CH3CHO",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(65600,'cm^3/(mol*s)'), n=2.86, Ea=(363.59,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 3 CH4 + CO <=> C2H4O in 1,2_Insertion_CO/training
    This reaction matched rate rule [CO;C_methane]
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Matched reaction 3 CH4 + CO <=> C2H4O in 1,2_Insertion_CO/training
This reaction matched rate rule [CO;C_methane]
family: 1,2_Insertion_CO
""",
)

entry(
    index = 34,
    label = "HCO + CH3 <=> CH3CHO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81e+13,'cm^3/(mol*s)','*|/',2), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 71 CH3 + CHO <=> C2H4O in R_Recombination/training
    This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_N-Sp-3R!H-2R_3R!H->O]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 71 CH3 + CHO <=> C2H4O in R_Recombination/training
This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_N-Sp-3R!H-2R_3R!H->O]
family: R_Recombination
""",
)

entry(
    index = 35,
    label = "CH3OO <=> O2 + CH3",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.09e+14,'s^-1'), n=0.25, Ea=(33.3,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 0 CH3O2 <=> O2 + CH3 in R_Recombination/training
    This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_2R->C_3R!H->O]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 0 CH3O2 <=> O2 + CH3 in R_Recombination/training
This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_2R->C_3R!H->O]
family: R_Recombination
""",
)

entry(
    index = 36,
    label = "CH3OO <=> OH + CH2O",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(4.71e+08,'s^-1'), n=1.45, Ea=(176.858,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""From training reaction 240 used for R3H_SS_O;O_rad_out;Cs_H_out_2H
    Exact match found for rate rule [R3H_SS_O;O_rad_out;Cs_H_out_2H]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: intra_H_migration"""),
    longDesc = 
"""
From training reaction 240 used for R3H_SS_O;O_rad_out;Cs_H_out_2H
Exact match found for rate rule [R3H_SS_O;O_rad_out;Cs_H_out_2H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: intra_H_migration
""",
)

entry(
    index = 37,
    label = "X + H <=> HX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.85, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite] for rate rule [H;VacantSite]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite] for rate rule [H;VacantSite]
Euclidian distance = 1.0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 38,
    label = "X + CH4 <=> CH4X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.008, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 11 CH4 + X <=> CH4X in Surface_Adsorption_vdW/training
    This reaction matched rate rule [Adsorbate;VacantSite]
    family: Surface_Adsorption_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 11 CH4 + X <=> CH4X in Surface_Adsorption_vdW/training
This reaction matched rate rule [Adsorbate;VacantSite]
family: Surface_Adsorption_vdW
metal: None
""",
)

entry(
    index = 39,
    label = "X + CH3 <=> CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.85, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite] for rate rule [CH2-H;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite] for rate rule [CH2-H;VacantSite]
Euclidian distance = 2.0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 40,
    label = "X + H2 <=> H2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.008, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite] for rate rule [H2;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite] for rate rule [H2;VacantSite]
Euclidian distance = 2.0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 41,
    label = "X + OH <=> OHX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.85, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite] for rate rule [O-H;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite] for rate rule [O-H;VacantSite]
Euclidian distance = 2.0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 42,
    label = "X + HCO <=> CHOX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.85, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite] for rate rule [CH=O;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite] for rate rule [CH=O;VacantSite]
Euclidian distance = 2.0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 43,
    label = "X + X + CO2 <=> OX + COX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.02, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CO2;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative_Double"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CO2;VacantSite1;VacantSite2]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative_Double
""",
)

entry(
    index = 44,
    label = "X + X + H2O <=> HX + OHX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.03, n=0, Ea=(61.9349,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 59.0 to 61.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 59.0 to 61.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 45,
    label = "X + X + C2H6 <=> CH3X + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.015, n=0, Ea=(5,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 46,
    label = "X + X + CH2O <=> HX + CHOX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.03, n=0, Ea=(5,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [C-H;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [C-H;VacantSite1;VacantSite2]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 47,
    label = "X + X + CH2O <=> OX + CH2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [OC;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative_Double"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [OC;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative_Double
""",
)

entry(
    index = 48,
    label = "X + X + CH3OH <=> OHX + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.015, n=0, Ea=(5,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 49,
    label = "X + X + CH3CHO <=> CHOX + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.015, n=0, Ea=(5,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 50,
    label = "X + X + C2H4 <=> CH2X + CH2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CC;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative_Double"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CC;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative_Double
""",
)

entry(
    index = 51,
    label = "X + CH4X <=> HX + CH3X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(1.54e+21,'cm^2/(mol*s)'), n=0.087, Ea=(55.8,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 12 CH4* + X_4 <=> CH3* + H* in Surface_Dissociation_vdW/training
    This reaction matched rate rule [C-H;VacantSite]
    family: Surface_Dissociation_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 12 CH4* + X_4 <=> CH3* + H* in Surface_Dissociation_vdW/training
This reaction matched rate rule [C-H;VacantSite]
family: Surface_Dissociation_vdW
metal: None
""",
)

entry(
    index = 52,
    label = "HX + COX <=> X + CHOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.14e+17,'m^2/(mol*s)'), n=0, Ea=(0.99,'eV/molecule'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 26 OCX_3 + HX_5 <=> CXHO_1 + Ni_4 in Surface_Dissociation/training
    This reaction matched rate rule [C-H;VacantSite]
    family: Surface_Dissociation
    metal: None"""),
    longDesc = 
"""
Matched reaction 26 OCX_3 + HX_5 <=> CXHO_1 + Ni_4 in Surface_Dissociation/training
This reaction matched rate rule [C-H;VacantSite]
family: Surface_Dissociation
metal: None
""",
)

entry(
    index = 53,
    label = "HCO + CH3 <=> CO + CH4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K'), Tmin=(1004,'K'), Tmax=(1006,'K'), comment="""Matched reaction 3 HCO + CH3 <=> CO + CH4 in CO_Disproportionation/training
    This reaction matched rate rule [C_methyl;HCO]
    family: CO_Disproportionation"""),
    longDesc = 
"""
Matched reaction 3 HCO + CH3 <=> CO + CH4 in CO_Disproportionation/training
This reaction matched rate rule [C_methyl;HCO]
family: CO_Disproportionation
""",
)

entry(
    index = 54,
    label = "H + CH4 <=> H2 + CH3",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(4100,'cm^3/(mol*s)'), n=3.156, Ea=(8755,'cal/mol'), T0=(1,'K'), comment="""Matched reaction 186 CH4b + H <=> CH3_p1 + H2_p in H_Abstraction/training
    This reaction matched rate rule [C_methane;H_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 186 CH4b + H <=> CH3_p1 + H2_p in H_Abstraction/training
This reaction matched rate rule [C_methane;H_rad]
family: H_Abstraction
""",
)

entry(
    index = 55,
    label = "CH3 + C2H6 <=> CH4 + C2H5",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(35,'cm^3/(mol*s)'), n=3.44, Ea=(10384,'cal/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(2000,'K'), comment="""Matched reaction 215 C2H6 + CH3_r3 <=> C2H5b + CH4 in H_Abstraction/training
    This reaction matched rate rule [C_methane;C_rad/H2/Cs\H3]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 215 C2H6 + CH3_r3 <=> C2H5b + CH4 in H_Abstraction/training
This reaction matched rate rule [C_methane;C_rad/H2/Cs\H3]
family: H_Abstraction
""",
)

entry(
    index = 56,
    label = "HCO + CH4 <=> CH2O + CH3",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(7280,'cm^3/(mol*s)','*|/',5), n=2.85, Ea=(143.302,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 318 HCO_r3 + CH4b <=> CH2O + CH3_p1 in H_Abstraction/training
    This reaction matched rate rule [C_methane;CO_pri_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 318 HCO_r3 + CH4b <=> CH2O + CH3_p1 in H_Abstraction/training
This reaction matched rate rule [C_methane;CO_pri_rad]
family: H_Abstraction
""",
)

entry(
    index = 57,
    label = "OH + CH4 <=> H2O + CH3",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(1e+06,'cm^3/(mol*s)'), n=2.182, Ea=(2506,'cal/mol'), T0=(1,'K'), comment="""Matched reaction 188 CH4b + OH <=> CH3_p1 + H2O_p in H_Abstraction/training
    This reaction matched rate rule [C_methane;O_pri_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 188 CH4b + OH <=> CH3_p1 + H2O_p in H_Abstraction/training
This reaction matched rate rule [C_methane;O_pri_rad]
family: H_Abstraction
""",
)

entry(
    index = 58,
    label = "CH3 + C2H5 <=> CH4 + C2H4",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(6.57e+14,'cm^3/(mol*s)','*|/',1.1), n=-0.68, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 5 CH3 + C2H5 <=> CH4 + C2H4 in Disproportionation/training
    This reaction matched rate rule [C_methyl;Cmethyl_Csrad]
    family: Disproportionation"""),
    longDesc = 
"""
Matched reaction 5 CH3 + C2H5 <=> CH4 + C2H4 in Disproportionation/training
This reaction matched rate rule [C_methyl;Cmethyl_Csrad]
family: Disproportionation
""",
)

entry(
    index = 59,
    label = "OH + HCO <=> H2O + CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.24e+23,'cm^3/(mol*s)'), n=-3.29, Ea=(9.85332,'kJ/mol'), T0=(1,'K'), Tmin=(1140,'K'), Tmax=(1650,'K'), comment="""Estimated using template [O_rad;HCO] for rate rule [O_pri_rad;HCO]
    Euclidian distance = 1.0
    family: CO_Disproportionation"""),
    longDesc = 
"""
Estimated using template [O_rad;HCO] for rate rule [O_pri_rad;HCO]
Euclidian distance = 1.0
family: CO_Disproportionation
""",
)

entry(
    index = 60,
    label = "OH + C2H6 <=> H2O + C2H5",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(1.61e+06,'cm^3/(mol*s)'), n=2.224, Ea=(740.73,'cal/mol'), T0=(1,'K'), comment="""Matched reaction 212 C2H6 + OH <=> C2H5b + H2O_p in H_Abstraction/training
    This reaction matched rate rule [O_pri;C_rad/H2/Cs\H3]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 212 C2H6 + OH <=> C2H5b + H2O_p in H_Abstraction/training
This reaction matched rate rule [O_pri;C_rad/H2/Cs\H3]
family: H_Abstraction
""",
)

entry(
    index = 61,
    label = "OH + CH2O <=> H2O + HCO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.44e+09,'cm^3/(mol*s)','*|/',5), n=1.18, Ea=(-1.8828,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K'), comment="""Matched reaction 367 OH_p23 + CH2O <=> H2O + HCO_r3 in H_Abstraction/training
    This reaction matched rate rule [O_pri;CO_pri_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 367 OH_p23 + CH2O <=> H2O + HCO_r3 in H_Abstraction/training
This reaction matched rate rule [O_pri;CO_pri_rad]
family: H_Abstraction
""",
)

entry(
    index = 62,
    label = "OH + C2H5 <=> H2O + C2H4",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(7.23e+13,'cm^3/(mol*s)','*|/',3), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 13 HO + C2H5 <=> H2O + C2H4 in Disproportionation/training
    This reaction matched rate rule [O_pri_rad;Cmethyl_Csrad]
    family: Disproportionation"""),
    longDesc = 
"""
Matched reaction 13 HO + C2H5 <=> H2O + C2H4 in Disproportionation/training
This reaction matched rate rule [O_pri_rad;Cmethyl_Csrad]
family: Disproportionation
""",
)

entry(
    index = 63,
    label = "H + HCO <=> H2 + CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.03e+13,'cm^3/(mol*s)','*|/',2), n=0, Ea=(0,'cal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 0 HCO + H <=> CO + H2 in CO_Disproportionation/training
    This reaction matched rate rule [H_rad;HCO]
    family: CO_Disproportionation"""),
    longDesc = 
"""
Matched reaction 0 HCO + H <=> CO + H2 in CO_Disproportionation/training
This reaction matched rate rule [H_rad;HCO]
family: CO_Disproportionation
""",
)

entry(
    index = 64,
    label = "H + C2H6 <=> H2 + C2H5",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(1.15e+08,'cm^3/(mol*s)'), n=1.9, Ea=(7530,'cal/mol'), T0=(1,'K'), comment="""Matched reaction 210 C2H6 + H <=> C2H5b + H2_p in H_Abstraction/training
    This reaction matched rate rule [H2;C_rad/H2/Cs\H3]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 210 C2H6 + H <=> C2H5b + H2_p in H_Abstraction/training
This reaction matched rate rule [H2;C_rad/H2/Cs\H3]
family: H_Abstraction
""",
)

entry(
    index = 65,
    label = "H2 + HCO <=> H + CH2O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.8e+06,'cm^3/(mol*s)','*|/',5), n=2, Ea=(204.765,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 309 H2 + HCO_r3 <=> CH2O + H in H_Abstraction/training
    This reaction matched rate rule [H2;CO_pri_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 309 H2 + HCO_r3 <=> CH2O + H in H_Abstraction/training
This reaction matched rate rule [H2;CO_pri_rad]
family: H_Abstraction
""",
)

entry(
    index = 66,
    label = "H + C2H5 <=> H2 + C2H4",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(1.083e+13,'cm^3/(mol*s)','*|/',2), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 4 H + C2H5 <=> H2 + C2H4 in Disproportionation/training
    This reaction matched rate rule [H_rad;Cmethyl_Csrad]
    family: Disproportionation"""),
    longDesc = 
"""
Matched reaction 4 H + C2H5 <=> H2 + C2H4 in Disproportionation/training
This reaction matched rate rule [H_rad;Cmethyl_Csrad]
family: Disproportionation
""",
)

entry(
    index = 67,
    label = "HCO + C2H5 <=> CO + C2H6",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.3e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K'), comment="""Matched reaction 12 C2H5 + HCO <=> C2H6 + CO in CO_Disproportionation/training
    This reaction matched rate rule [C_rad/H2/Cs;HCO]
    family: CO_Disproportionation"""),
    longDesc = 
"""
Matched reaction 12 C2H5 + HCO <=> C2H6 + CO in CO_Disproportionation/training
This reaction matched rate rule [C_rad/H2/Cs;HCO]
family: CO_Disproportionation
""",
)

entry(
    index = 68,
    label = "HCO + HCO <=> CO + CH2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.8e+13,'cm^3/(mol*s)','+|-',9e+12), n=0, Ea=(0,'cal/mol'), T0=(1,'K'), comment="""Matched reaction 5 HCO + HCO_Y <=> CO + CH2O in CO_Disproportionation/training
    This reaction matched rate rule [CO_pri_rad;HCO]
    family: CO_Disproportionation"""),
    longDesc = 
"""
Matched reaction 5 HCO + HCO_Y <=> CO + CH2O in CO_Disproportionation/training
This reaction matched rate rule [CO_pri_rad;HCO]
family: CO_Disproportionation
""",
)

entry(
    index = 69,
    label = "HCO + C2H6 <=> CH2O + C2H5",
    degeneracy = 6.0,
    kinetics = Arrhenius(A=(46920,'cm^3/(mol*s)','*|/',5), n=2.72, Ea=(159.996,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 325 HCO_r3 + C2H6 <=> CH2O + C2H5 in H_Abstraction/training
    This reaction matched rate rule [C/H3/Cs\H3;CO_pri_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 325 HCO_r3 + C2H6 <=> CH2O + C2H5 in H_Abstraction/training
This reaction matched rate rule [C/H3/Cs\H3;CO_pri_rad]
family: H_Abstraction
""",
)

entry(
    index = 70,
    label = "C2H5 + C2H5 <=> C2H4 + C2H6",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(6.9e+13,'cm^3/(mol*s)','*|/',1.1), n=-0.35, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 6 C2H5 + C2H5-2 <=> C2H6 + C2H4 in Disproportionation/training
    This reaction matched rate rule [C_rad/H2/Cs;Cmethyl_Csrad]
    family: Disproportionation"""),
    longDesc = 
"""
Matched reaction 6 C2H5 + C2H5-2 <=> C2H6 + C2H4 in Disproportionation/training
This reaction matched rate rule [C_rad/H2/Cs;Cmethyl_Csrad]
family: Disproportionation
""",
)

entry(
    index = 71,
    label = "HCO + C2H5 <=> CH2O + C2H4",
    degeneracy = 3.0,
    kinetics = Arrhenius(A=(5.97286e+08,'m^3/(mol*s)'), n=-0.34, Ea=(0,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [Y_rad;Cmethyl_Csrad] + [CO_pri_rad;XH_s_Rrad] for rate rule [CO_pri_rad;Cmethyl_Csrad]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 3.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using average of templates [Y_rad;Cmethyl_Csrad] + [CO_pri_rad;XH_s_Rrad] for rate rule [CO_pri_rad;Cmethyl_Csrad]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 3.0
family: Disproportionation
""",
)

entry(
    index = 72,
    label = "H2X + CH3X <=> HX + CH4X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [H-H;*C-3R]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -29.7 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [H-H;*C-3R]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -29.7 to 0.0 kJ/mol.
""",
)

entry(
    index = 73,
    label = "H2X + CHX <=> HX + CH2X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*C] for rate rule [H-H;*#CH]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*C] for rate rule [H-H;*#CH]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 74,
    label = "H2X + CH2X <=> HX + CH3X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*=C] for rate rule [H-H;*=C-2R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=C] for rate rule [H-H;*=C-2R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 75,
    label = "H2X + CX <=> HX + CHX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*C] for rate rule [H-H;*$C]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*C] for rate rule [H-H;*$C]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 76,
    label = "OX + H2X <=> HX + OHX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.78261e+20,'m^2/(mol*s)'), n=-0.1875, Ea=(155.55,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*=O] for rate rule [H-H;*=O]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=O] for rate rule [H-H;*=O]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 77,
    label = "OHX + H2X <=> HX + H2OX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [H-H;*O-H]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -64.3 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [H-H;*O-H]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -64.3 to 0.0 kJ/mol.
""",
)

entry(
    index = 78,
    label = "H2X + COX <=> HX + CHOX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [AdsorbateVdW;*=C=R] for rate rule [H-H;*=C=R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=C=R] for rate rule [H-H;*=C=R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 79,
    label = "COX + CH4X <=> CHOX + CH3X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4.14787e+13,'m^2/(mol*s)'), n=0.936633, Ea=(97.9184,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [AdsorbateVdW;*=C=R] for rate rule [C-R;*=C=R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW
    Ea raised from 95.5 to 97.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=C=R] for rate rule [C-R;*=C=R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
Ea raised from 95.5 to 97.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 80,
    label = "CHX + CHOX <=> COX + CH2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.20462e+18,'m^2/(mol*s)'), n=0.0505, Ea=(21.2,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [Abstracting;*-C-H] + [C#*;*R-H] for rate rule [C#*;*-C-H]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [Abstracting;*-C-H] + [C#*;*R-H] for rate rule [C#*;*-C-H]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 81,
    label = "CHOX + CH2X <=> COX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.14108e+17,'m^2/(mol*s)'), n=0.0505, Ea=(9.5,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [Abstracting;*-C-H] + [C=*;*R-H] for rate rule [C=*;*-C-H]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [Abstracting;*-C-H] + [C=*;*R-H] for rate rule [C=*;*-C-H]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 82,
    label = "CX + CHOX <=> COX + CHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.83093e+17,'m^2/(mol*s)'), n=-0.156, Ea=(59.45,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [Abstracting;*-C-H] + [C$*;*R-H] for rate rule [C$*;*-C-H]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [Abstracting;*-C-H] + [C$*;*R-H] for rate rule [C$*;*-C-H]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 83,
    label = "OX + CHOX <=> OHX + COX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.298e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 39 O* + HCO* <=> OH* + CO* in Surface_Abstraction/training
    This reaction matched rate rule [C=*;*OH]
    family: Surface_Abstraction
    metal: None"""),
    longDesc = 
"""
Matched reaction 39 O* + HCO* <=> OH* + CO* in Surface_Abstraction/training
This reaction matched rate rule [C=*;*OH]
family: Surface_Abstraction
metal: None
""",
)

entry(
    index = 84,
    label = "OHX + CHOX <=> H2OX + COX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.261e+17,'m^2/(mol*s)'), n=0, Ea=(0.3,'eV/molecule'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 40 OH_2* + HCO* <=> H2O* + CO* in Surface_Abstraction_vdW/training
    This reaction matched rate rule [O-R;*=C=R]
    family: Surface_Abstraction_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 40 OH_2* + HCO* <=> H2O* + CO* in Surface_Abstraction_vdW/training
This reaction matched rate rule [O-R;*=C=R]
family: Surface_Abstraction_vdW
metal: None
""",
)

entry(
    index = 85,
    label = "OX + CH4X <=> OHX + CH3X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(5.62e+20,'m^2/(mol*s)'), n=-0.101, Ea=(92700,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 21 CH4* + O* <=> CH3* + OH_4* in Surface_Abstraction_vdW/training
    This reaction matched rate rule [C-R;*=O]
    family: Surface_Abstraction_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 21 CH4* + O* <=> CH3* + OH_4* in Surface_Abstraction_vdW/training
This reaction matched rate rule [C-R;*=O]
family: Surface_Abstraction_vdW
metal: None
""",
)

entry(
    index = 86,
    label = "CH2X + CH4X <=> CH3X + CH3X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4.14787e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*=C] for rate rule [C-R;*=C-2R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=C] for rate rule [C-R;*=C-2R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 87,
    label = "CHX + CH4X <=> CH2X + CH3X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4.14787e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*C] for rate rule [C-R;*#CH]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*C] for rate rule [C-R;*#CH]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 88,
    label = "CX + CH4X <=> CHX + CH3X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4.14787e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*C] for rate rule [C-R;*$C]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*C] for rate rule [C-R;*$C]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 89,
    label = "OHX + CH4X <=> H2OX + CH3X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -34.6 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_Single_vdW
Ea raised from -34.6 to 0.0 kJ/mol.
""",
)

entry(
    index = 90,
    label = "OHX + CHX <=> OX + CH2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.4e+18,'m^2/(mol*s)'), n=0.101, Ea=(42867.9,'J/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 26 CHX_1 + HOX_3 <=> CH2X_4 + OX_5 in Surface_Abstraction/training
    This reaction matched rate rule [O;*=C-H]
    family: Surface_Abstraction
    metal: None
    Ea raised from 42.4 to 42.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 26 CHX_1 + HOX_3 <=> CH2X_4 + OX_5 in Surface_Abstraction/training
This reaction matched rate rule [O;*=C-H]
family: Surface_Abstraction
metal: None
Ea raised from 42.4 to 42.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 91,
    label = "OHX + CH2X <=> OX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.39e+17,'m^2/(mol*s)'), n=0.101, Ea=(19000,'J/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 24 CH2X_1 + HOX_3 <=> CH3X_4 + OX_5 in Surface_Abstraction/training
    This reaction matched rate rule [O;*-C-H]
    family: Surface_Abstraction
    metal: None"""),
    longDesc = 
"""
Matched reaction 24 CH2X_1 + HOX_3 <=> CH3X_4 + OX_5 in Surface_Abstraction/training
This reaction matched rate rule [O;*-C-H]
family: Surface_Abstraction
metal: None
""",
)

entry(
    index = 92,
    label = "OHX + CX <=> OX + CHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.43e+17,'m^2/(mol*s)'), n=-0.312, Ea=(118900,'J/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 28 HOX_3 + CX_1 <=> OX_5 + CHX_4  in Surface_Abstraction/training
    This reaction matched rate rule [O;*#C-H]
    family: Surface_Abstraction
    metal: None"""),
    longDesc = 
"""
Matched reaction 28 HOX_3 + CX_1 <=> OX_5 + CHX_4  in Surface_Abstraction/training
This reaction matched rate rule [O;*#C-H]
family: Surface_Abstraction
metal: None
""",
)

entry(
    index = 93,
    label = "CH2X + CH2X <=> CHX + CH3X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.78e+17,'m^2/(mol*s)'), n=0.101, Ea=(19,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C=*;*R-H] for rate rule [C=*;*=C-H]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C=*;*R-H] for rate rule [C=*;*=C-H]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 94,
    label = "CX + CH3X <=> CHX + CH2X",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(8.49278e+17,'m^2/(mol*s)'), n=-0.156, Ea=(59.45,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [Abstracting;*-C-H] + [C$*;*R-H] for rate rule [C$*;*-C-H]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [Abstracting;*-C-H] + [C$*;*R-H] for rate rule [C$*;*-C-H]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction
""",
)

entry(
    index = 95,
    label = "CX + CH2X <=> CHX + CHX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.86e+17,'m^2/(mol*s)'), n=-0.312, Ea=(118.9,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C$*;*R-H] for rate rule [C$*;*=C-H]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C$*;*R-H] for rate rule [C$*;*=C-H]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 96,
    label = "H2OX + CHX <=> OHX + CH2X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(133.67,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O-R;*C] for rate rule [O-R;*#CH]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;*C] for rate rule [O-R;*#CH]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 97,
    label = "H2OX + CH2X <=> OHX + CH3X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O-R;*=C] for rate rule [O-R;*=C-2R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;*=C] for rate rule [O-R;*=C-2R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 98,
    label = "H2OX + CX <=> OHX + CHX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O-R;*C] for rate rule [O-R;*$C]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;*C] for rate rule [O-R;*$C]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 99,
    label = "HX + CHOX <=> X + HCOH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.048e+17,'m^2/(mol*s)'), n=0, Ea=(0.91,'eV/molecule'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 29 HCO* + H* <=> HCOH* + Cu in Surface_Dissociation_Beta/training
    This reaction matched rate rule [*-C=O;H-*]
    family: Surface_Dissociation_Beta
    metal: None"""),
    longDesc = 
"""
Matched reaction 29 HCO* + H* <=> HCOH* + Cu in Surface_Dissociation_Beta/training
This reaction matched rate rule [*-C=O;H-*]
family: Surface_Dissociation_Beta
metal: None
""",
)

entry(
    index = 100,
    label = "X + HCOH_ads <=> OHX + CHX",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1.46e+20,'m^2/(mol*s)'), n=-0.213, Ea=(54.3,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [C-O;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [C-O;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 101,
    label = "H2OX + CHX <=> HX + HCOH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*C] for rate rule [AdsorbateVdW;*#CH]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*C] for rate rule [AdsorbateVdW;*#CH]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 102,
    label = "X + HCOH_ads <=> OHX + CHX",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1.46e+20,'m^2/(mol*s)'), n=-0.213, Ea=(54.3,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [C-O;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [C-O;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 103,
    label = "HX + COX <=> X + COH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.799e+17,'m^2/(mol*s)'), n=0, Ea=(2.26,'eV/molecule'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 27 CO* + H* <=> COH* + Cu in Surface_Dissociation_Beta/training
    This reaction matched rate rule [*=C=O;H-*]
    family: Surface_Dissociation_Beta
    metal: None"""),
    longDesc = 
"""
Matched reaction 27 CO* + H* <=> COH* + Cu in Surface_Dissociation_Beta/training
This reaction matched rate rule [*=C=O;H-*]
family: Surface_Dissociation_Beta
metal: None
""",
)

entry(
    index = 104,
    label = "X + COH_ads <=> OHX + CX",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1.46e+20,'m^2/(mol*s)'), n=-0.213, Ea=(147.341,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [C-O;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [C-O;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 105,
    label = "H2OX + CX <=> HX + COH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*C] for rate rule [AdsorbateVdW;*$C]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*C] for rate rule [AdsorbateVdW;*$C]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 106,
    label = "X + HCOH_ads <=> HX + COH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.71e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 48 used for C-H;VacantSite
    Exact match found for rate rule [C-H;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
From training reaction 48 used for C-H;VacantSite
Exact match found for rate rule [C-H;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 107,
    label = "H2X + COH_ads <=> HX + HCOH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*C] for rate rule [H-H;*#C]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*C] for rate rule [H-H;*#C]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 108,
    label = "CHOX + COH_ads <=> COX + HCOH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.20462e+18,'m^2/(mol*s)'), n=0.0505, Ea=(21.2,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [Abstracting;*-C-H] + [C#*;*R-H] for rate rule [C#*;*-C-H]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [Abstracting;*-C-H] + [C#*;*R-H] for rate rule [C#*;*-C-H]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 109,
    label = "OHX + COH_ads <=> OX + HCOH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.4e+18,'m^2/(mol*s)'), n=0.101, Ea=(56.5538,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 26 used for C#*;*OH
    Exact match found for rate rule [C#*;*OH]
    Euclidian distance = 0
    family: Surface_Abstraction
    Ea raised from 53.7 to 56.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
From training reaction 26 used for C#*;*OH
Exact match found for rate rule [C#*;*OH]
Euclidian distance = 0
family: Surface_Abstraction
Ea raised from 53.7 to 56.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 110,
    label = "CH2X + HCOH_ads <=> COH_ads + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.39e+17,'m^2/(mol*s)'), n=0.101, Ea=(19,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C=*;*R-H] for rate rule [C=*;*=C-H]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C=*;*R-H] for rate rule [C=*;*=C-H]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 111,
    label = "COH_ads + CH4X <=> HCOH_ads + CH3X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4.14787e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*C] for rate rule [C-R;*#C]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*C] for rate rule [C-R;*#C]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 112,
    label = "CHX + HCOH_ads <=> COH_ads + CH2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.4e+18,'m^2/(mol*s)'), n=0.101, Ea=(42.4,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C#*;*R-H] for rate rule [C#*;*=C-H]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C#*;*R-H] for rate rule [C#*;*=C-H]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 113,
    label = "CX + HCOH_ads <=> CHX + COH_ads",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.43e+17,'m^2/(mol*s)'), n=-0.312, Ea=(118.9,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C$*;Donating] for rate rule [C$*;*=C-OH]
    Euclidian distance = 4.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C$*;Donating] for rate rule [C$*;*=C-OH]
Euclidian distance = 4.0
family: Surface_Abstraction
""",
)

entry(
    index = 114,
    label = "CX + HCOH_ads <=> CHX + COH_ads",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.43e+17,'m^2/(mol*s)'), n=-0.312, Ea=(118.9,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C$*;*R-H] for rate rule [C$*;*=C-H]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C$*;*R-H] for rate rule [C$*;*=C-H]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 115,
    label = "H2OX + COH_ads <=> OHX + HCOH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(147.06,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O-R;*C] for rate rule [O-R;*#C]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 146.0 to 147.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [O-R;*C] for rate rule [O-R;*#C]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 146.0 to 147.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 116,
    label = "X + COH_ads <=> OHX + CX",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1.46e+20,'m^2/(mol*s)'), n=-0.213, Ea=(147.341,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [C-O;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [C-O;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 117,
    label = "CX + HCOH_ads <=> CHX + COH_ads",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.43e+17,'m^2/(mol*s)'), n=-0.312, Ea=(118.9,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C$*;Donating] for rate rule [C$*;*=C-OH]
    Euclidian distance = 4.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C$*;Donating] for rate rule [C$*;*=C-OH]
Euclidian distance = 4.0
family: Surface_Abstraction
""",
)

entry(
    index = 118,
    label = "CX + HCOH_ads <=> CHX + COH_ads",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.43e+17,'m^2/(mol*s)'), n=-0.312, Ea=(118.9,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C$*;Donating] for rate rule [C$*;*=C-OH]
    Euclidian distance = 4.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C$*;Donating] for rate rule [C$*;*=C-OH]
Euclidian distance = 4.0
family: Surface_Abstraction
""",
)

entry(
    index = 119,
    label = "X + O=CC#[Pt] <=> CX + CHOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(7.35976e+18,'m^2/(mol*s)'), n=-0.1065, Ea=(79.4536,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [C;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation
    Ea raised from 77.2 to 79.5 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using an average for rate rule [C;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
Ea raised from 77.2 to 79.5 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 120,
    label = "CX + CH4X <=> HX + C-CH3_ads",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4.14787e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*C] for rate rule [AdsorbateVdW;*$C]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*C] for rate rule [AdsorbateVdW;*$C]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 121,
    label = "X + C-CH3_ads <=> CX + CH3X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(7.35976e+18,'m^2/(mol*s)'), n=-0.1065, Ea=(93.6115,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [C;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [C;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 122,
    label = "X + C-CH3_ads <=> CX + CH3X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(7.35976e+18,'m^2/(mol*s)'), n=-0.1065, Ea=(93.6115,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [C;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [C;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 123,
    label = "X + X + CH3OH <=> HX + H2C-OH_ads",
    degeneracy = 3.0,
    kinetics = StickingCoefficient(A=0.045, n=0, Ea=(5,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [C-H;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [C-H;VacantSite1;VacantSite2]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 3.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 124,
    label = "HX + CH2O <=> H2C-OH_ads",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.05, n=0, Ea=(73.06,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
    Euclidian distance = 1.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
Euclidian distance = 1.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 125,
    label = "X + H2C-OH_ads <=> OHX + CH2X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1.46e+20,'m^2/(mol*s)'), n=-0.213, Ea=(130.204,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 4 used for C-OH;VacantSite
    Exact match found for rate rule [C-OH;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
From training reaction 4 used for C-OH;VacantSite
Exact match found for rate rule [C-OH;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 126,
    label = "H2OX + CH2X <=> HX + H2C-OH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*=C] for rate rule [AdsorbateVdW;*=C-2R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=C] for rate rule [AdsorbateVdW;*=C-2R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 127,
    label = "X + H2C-OH_ads <=> HX + HCOH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(7.42e+17,'m^2/(mol*s)'), n=0, Ea=(47.0676,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 48 used for C-H;VacantSite
    Exact match found for rate rule [C-H;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation
    Ea raised from 0.0 to 47.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
From training reaction 48 used for C-H;VacantSite
Exact match found for rate rule [C-H;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation
Ea raised from 0.0 to 47.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 128,
    label = "HCOH_ads + CH4X <=> CH3X + H2C-OH_ads",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4.14787e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*=C] for rate rule [C-R;*=C-2R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=C] for rate rule [C-R;*=C-2R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 129,
    label = "CH2X + HCOH_ads <=> CHX + H2C-OH_ads",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1.39e+17,'m^2/(mol*s)'), n=0.101, Ea=(19,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C=*;Donating] for rate rule [C=*;*=C-OH]
    Euclidian distance = 4.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C=*;Donating] for rate rule [C=*;*=C-OH]
Euclidian distance = 4.0
family: Surface_Abstraction
""",
)

entry(
    index = 130,
    label = "CH2X + HCOH_ads <=> CHX + H2C-OH_ads",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.78e+17,'m^2/(mol*s)'), n=0.101, Ea=(19,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C=*;*R-H] for rate rule [C=*;*=C-H]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C=*;*R-H] for rate rule [C=*;*=C-H]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 131,
    label = "HCOH_ads + CH3X <=> CH2X + H2C-OH_ads",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(6.42324e+17,'m^2/(mol*s)'), n=0.0505, Ea=(9.5,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [Abstracting;*-C-H] + [C=*;*R-H] for rate rule [C=*;*-C-H]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [Abstracting;*-C-H] + [C=*;*R-H] for rate rule [C=*;*-C-H]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction
""",
)

entry(
    index = 132,
    label = "CX + H2C-OH_ads <=> CHX + HCOH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(5.66185e+17,'m^2/(mol*s)'), n=-0.156, Ea=(59.45,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [Abstracting;*-C-H] + [C$*;*R-H] for rate rule [C$*;*-C-H]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [Abstracting;*-C-H] + [C$*;*R-H] for rate rule [C$*;*-C-H]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 133,
    label = "H2X + HCOH_ads <=> HX + H2C-OH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*=C] for rate rule [H-H;*=C-2R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=C] for rate rule [H-H;*=C-2R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 134,
    label = "OX + H2C-OH_ads <=> OHX + HCOH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.596e+17,'m^2/(mol*s)'), n=0, Ea=(57.5612,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 39 used for O;*-C-H
    Exact match found for rate rule [O;*-C-H]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction
    Ea raised from 0.0 to 57.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
From training reaction 39 used for O;*-C-H
Exact match found for rate rule [O;*-C-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
Ea raised from 0.0 to 57.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 135,
    label = "H2OX + HCOH_ads <=> OHX + H2C-OH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O-R;*=C] for rate rule [O-R;*=C-2R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;*=C] for rate rule [O-R;*=C-2R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 136,
    label = "CHOX + HCOH_ads <=> COX + H2C-OH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.14108e+17,'m^2/(mol*s)'), n=0.0505, Ea=(9.5,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [Abstracting;*-C-H] + [C=*;*R-H] for rate rule [C=*;*-C-H]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [Abstracting;*-C-H] + [C=*;*R-H] for rate rule [C=*;*-C-H]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 137,
    label = "HCOH_ads + HCOH_ads <=> COH_ads + H2C-OH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.39e+17,'m^2/(mol*s)'), n=0.101, Ea=(19,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C=*;*R-H] for rate rule [C=*;*=C-H]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C=*;*R-H] for rate rule [C=*;*=C-H]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 138,
    label = "CX + H2C-OH_ads <=> COH_ads + CH2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.43e+17,'m^2/(mol*s)'), n=-0.312, Ea=(118.9,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C$*;Donating] for rate rule [C$*;*-C-OH]
    Euclidian distance = 4.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C$*;Donating] for rate rule [C$*;*-C-OH]
Euclidian distance = 4.0
family: Surface_Abstraction
""",
)

entry(
    index = 139,
    label = "X + H2C-OH_ads <=> OHX + CH2X",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1.46e+20,'m^2/(mol*s)'), n=-0.213, Ea=(130.204,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 4 used for C-OH;VacantSite
    Exact match found for rate rule [C-OH;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
From training reaction 4 used for C-OH;VacantSite
Exact match found for rate rule [C-OH;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 140,
    label = "CH2X + HCOH_ads <=> CHX + H2C-OH_ads",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1.39e+17,'m^2/(mol*s)'), n=0.101, Ea=(19,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C=*;Donating] for rate rule [C=*;*=C-OH]
    Euclidian distance = 4.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C=*;Donating] for rate rule [C=*;*=C-OH]
Euclidian distance = 4.0
family: Surface_Abstraction
""",
)

entry(
    index = 141,
    label = "CH2X + HCOH_ads <=> CHX + H2C-OH_ads",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.78e+17,'m^2/(mol*s)'), n=0.101, Ea=(19,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C=*;*R-H] for rate rule [C=*;*=C-H]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C=*;*R-H] for rate rule [C=*;*=C-H]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 142,
    label = "X + ketene(T)X <=> CHX + CHOX",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(7.35976e+18,'m^2/(mol*s)'), n=-0.1065, Ea=(27.15,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [C;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [C;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 143,
    label = "X + ketene(T)X <=> HX + O=CC#[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.71e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 48 used for C-H;VacantSite
    Exact match found for rate rule [C-H;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
From training reaction 48 used for C-H;VacantSite
Exact match found for rate rule [C-H;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 144,
    label = "CH4X + O=CC#[Pt] <=> CH3X + ketene(T)X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4.14787e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*C] for rate rule [C-R;*#C]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*C] for rate rule [C-R;*#C]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 145,
    label = "CH2X + O=CC#[Pt] <=> CHX + ketene(T)X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(8.8e+18,'m^2/(mol*s)'), n=0.101, Ea=(42.4,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C#*;*R-H] for rate rule [C#*;*=C-H]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C#*;*R-H] for rate rule [C#*;*=C-H]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 146,
    label = "CH2X + ketene(T)X <=> CH3X + O=CC#[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.39e+17,'m^2/(mol*s)'), n=0.101, Ea=(19,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C=*;*R-H] for rate rule [C=*;*=C-H]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C=*;*R-H] for rate rule [C=*;*=C-H]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 147,
    label = "CX + ketene(T)X <=> CHX + O=CC#[Pt]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.43e+17,'m^2/(mol*s)'), n=-0.312, Ea=(118.9,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C$*;Donating] for rate rule [C$*;*C-C]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C$*;Donating] for rate rule [C$*;*C-C]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 148,
    label = "CX + ketene(T)X <=> CHX + O=CC#[Pt]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.43e+17,'m^2/(mol*s)'), n=-0.312, Ea=(118.9,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C$*;Donating] for rate rule [C$*;*C-C]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C$*;Donating] for rate rule [C$*;*C-C]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 149,
    label = "H2X + O=CC#[Pt] <=> HX + ketene(T)X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(86.4628,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*C] for rate rule [H-H;*#C]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*C] for rate rule [H-H;*#C]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 150,
    label = "OHX + O=CC#[Pt] <=> OX + ketene(T)X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.4e+18,'m^2/(mol*s)'), n=0.101, Ea=(42.4,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 26 used for C#*;*OH
    Exact match found for rate rule [C#*;*OH]
    Euclidian distance = 0
    family: Surface_Abstraction"""),
    longDesc = 
"""
From training reaction 26 used for C#*;*OH
Exact match found for rate rule [C#*;*OH]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 151,
    label = "H2OX + O=CC#[Pt] <=> OHX + ketene(T)X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(128.632,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O-R;*C] for rate rule [O-R;*#C]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 127.6 to 128.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [O-R;*C] for rate rule [O-R;*#C]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 127.6 to 128.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 152,
    label = "CHOX + O=CC#[Pt] <=> COX + ketene(T)X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.20462e+18,'m^2/(mol*s)'), n=0.0505, Ea=(21.2,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [Abstracting;*-C-H] + [C#*;*R-H] for rate rule [C#*;*-C-H]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [Abstracting;*-C-H] + [C#*;*R-H] for rate rule [C#*;*-C-H]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 153,
    label = "HCOH_ads + O=CC#[Pt] <=> COH_ads + ketene(T)X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.4e+18,'m^2/(mol*s)'), n=0.101, Ea=(42.4,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C#*;*R-H] for rate rule [C#*;*=C-H]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C#*;*R-H] for rate rule [C#*;*=C-H]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 154,
    label = "HCOH_ads + ketene(T)X <=> H2C-OH_ads + O=CC#[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.39e+17,'m^2/(mol*s)'), n=0.101, Ea=(19,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C=*;*R-H] for rate rule [C=*;*=C-H]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C=*;*R-H] for rate rule [C=*;*=C-H]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 155,
    label = "X + ketene(T)X <=> CHX + CHOX",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(7.35976e+18,'m^2/(mol*s)'), n=-0.1065, Ea=(27.15,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [C;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [C;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 156,
    label = "CX + ketene(T)X <=> CHX + O=CC#[Pt]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.43e+17,'m^2/(mol*s)'), n=-0.312, Ea=(118.9,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C$*;Donating] for rate rule [C$*;*C-C]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C$*;Donating] for rate rule [C$*;*C-C]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 157,
    label = "CX + ketene(T)X <=> CHX + O=CC#[Pt]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(2.43e+17,'m^2/(mol*s)'), n=-0.312, Ea=(118.9,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C$*;*R-H] for rate rule [C$*;*=C-H]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [C$*;*R-H] for rate rule [C$*;*=C-H]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 158,
    label = "CHCH3(S) <=> C2H4",
    degeneracy = 3.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.84394e+15,'s^-1'), n=-1.07844, Ea=(56.8484,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CsJ2-C;singletcarbene;CH] for rate rule [CsJ2-C;CsJ2H;CH3]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 3.0
    family: Singlet_Carbene_Intra_Disproportionation"""),
    longDesc = 
"""
Estimated using template [CsJ2-C;singletcarbene;CH] for rate rule [CsJ2-C;CsJ2H;CH3]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 3.0
family: Singlet_Carbene_Intra_Disproportionation
""",
)

entry(
    index = 159,
    label = "CHCH3(S) <=> C2H4",
    degeneracy = 3.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.84394e+15,'s^-1'), n=-1.07844, Ea=(56.8484,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CsJ2-C;singletcarbene;CH] for rate rule [CsJ2-C;CsJ2H;CH3]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 3.0
    family: Singlet_Carbene_Intra_Disproportionation"""),
    longDesc = 
"""
Estimated using template [CsJ2-C;singletcarbene;CH] for rate rule [CsJ2-C;CsJ2H;CH3]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 3.0
family: Singlet_Carbene_Intra_Disproportionation
""",
)

entry(
    index = 160,
    label = "X + X + CHCH3(S) <=> CHX + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.015, n=0, Ea=(5,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 161,
    label = "X + X + CHCH3(S) <=> HX + C-CH3_ads",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.015, n=0, Ea=(5,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

